version: "3.3"
services:
  server:
    build: ./server
    container_name: server_c
    ports:
      - "5000:5000"
  client:
    build: ./client
    container_name: client_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
