name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the client Docker image
        # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        run: docker build -f client/Dockerfile -t labdash/dockerize-vuejs-app-client
      - name: Build the server Docker image
        # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        run: docker build -f server/Dockerfile -t labdash/dockerize-vuejs-app-server
